import type { LoginResponse, Grade, Absence, AgendaEvent, Lesson, Notice, Subject } from "./classeviva-api"

export const mockLoginResponse: LoginResponse = {
  token: "mock_token_12345",
  release: "4.1.7",
  expire: "2024-12-31T23:59:59Z",
  ident: {
    id: 12345,
    firstName: "Mario",
    lastName: "Rossi",
    usrType: "S",
    usrId: 67890,
  },
}

export const mockGrades: Grade[] = [
  {
    subjectId: 1,
    subjectCode: "MAT",
    subjectDesc: "Matematica",
    evtId: 101,
    evtCode: "VTO",
    evtDate: "2024-01-15",
    decimalValue: 8.5,
    displayValue: "8½",
    displaPos: 1,
    notesForFamily: "Ottimo lavoro sui logaritmi",
    color: "green",
    canceled: false,
    underlined: false,
    periodPos: 1,
    periodDesc: "Primo Quadrimestre",
    componentPos: 1,
    componentDesc: "Scritto",
    weightFactor: 1,
    skillId: 1,
    gradeMasterId: 1,
  },
  {
    subjectId: 2,
    subjectCode: "ITA",
    subjectDesc: "Italiano",
    evtId: 102,
    evtCode: "VTO",
    evtDate: "2024-01-20",
    decimalValue: 7.0,
    displayValue: "7",
    displaPos: 2,
    notesForFamily: "Buona analisi del testo",
    color: "blue",
    canceled: false,
    underlined: false,
    periodPos: 1,
    periodDesc: "Primo Quadrimestre",
    componentPos: 1,
    componentDesc: "Scritto",
    weightFactor: 1,
    skillId: 2,
    gradeMasterId: 2,
  },
  {
    subjectId: 3,
    subjectCode: "STO",
    subjectDesc: "Storia",
    evtId: 103,
    evtCode: "VTO",
    evtDate: "2024-01-25",
    decimalValue: 9.0,
    displayValue: "9",
    displaPos: 3,
    notesForFamily: "Eccellente conoscenza del periodo storico",
    color: "green",
    canceled: false,
    underlined: false,
    periodPos: 1,
    periodDesc: "Primo Quadrimestre",
    componentPos: 2,
    componentDesc: "Orale",
    weightFactor: 1,
    skillId: 3,
    gradeMasterId: 3,
  },
  {
    subjectId: 4,
    subjectCode: "ING",
    subjectDesc: "Inglese",
    evtId: 104,
    evtCode: "VTO",
    evtDate: "2024-01-30",
    decimalValue: 6.5,
    displayValue: "6½",
    displaPos: 4,
    notesForFamily: "Migliorare la pronuncia",
    color: "yellow",
    canceled: false,
    underlined: false,
    periodPos: 1,
    periodDesc: "Primo Quadrimestre",
    componentPos: 2,
    componentDesc: "Orale",
    weightFactor: 1,
    skillId: 4,
    gradeMasterId: 4,
  },
]

export const mockAbsences: Absence[] = [
  {
    evtId: 201,
    evtCode: "A",
    evtDate: "2024-01-10",
    evtHPos: 2,
    evtValue: "Assenza",
    isJustified: true,
    justifReasonCode: "MAL",
    justifReasonDesc: "Malattia",
  },
  {
    evtId: 202,
    evtCode: "R",
    evtDate: "2024-01-18",
    evtHPos: 1,
    evtValue: "Ritardo",
    isJustified: true,
    justifReasonCode: "TRA",
    justifReasonDesc: "Problemi di trasporto",
  },
]

export const mockAgendaEvents: AgendaEvent[] = [
  {
    evtId: 301,
    evtStart: "20240205 0800",
    evtEnd: "20240205 0900",
    evtCode: "AGNT",
    evtDatetimeBegin: "2024-02-05T08:00:00",
    evtDatetimeEnd: "2024-02-05T09:00:00",
    classDesc: "3A",
    authorName: "Prof. Bianchi",
    subjectId: 1,
    subjectCode: "MAT",
    subjectDesc: "Matematica",
    evtText: "Verifica sui logaritmi",
    homeworkText: "Studiare capitolo 5 del libro di testo",
  },
  {
    evtId: 302,
    evtStart: "20240206 1000",
    evtEnd: "20240206 1100",
    evtCode: "AGNT",
    evtDatetimeBegin: "2024-02-06T10:00:00",
    evtDatetimeEnd: "2024-02-06T11:00:00",
    classDesc: "3A",
    authorName: "Prof. Verdi",
    subjectId: 2,
    subjectCode: "ITA",
    subjectDesc: "Italiano",
    evtText: "Analisi del testo poetico",
    homeworkText: "Leggere e analizzare la poesia a pagina 120",
  },
]

export const mockLessons: Lesson[] = [
  {
    evtId: 401,
    evtDate: "2024-02-05",
    evtHPos: 1,
    evtDuration: 1,
    classDesc: "3A",
    authorName: "Prof. Bianchi",
    subjectId: 1,
    subjectCode: "MAT",
    subjectDesc: "Matematica",
    lessonType: "Lezione",
    lessonArg: "Funzioni logaritmiche e loro proprietà",
  },
  {
    evtId: 402,
    evtDate: "2024-02-05",
    evtHPos: 2,
    evtDuration: 1,
    classDesc: "3A",
    authorName: "Prof. Verdi",
    subjectId: 2,
    subjectCode: "ITA",
    subjectDesc: "Italiano",
    lessonType: "Lezione",
    lessonArg: "Analisi del testo: Leopardi e l'infinito",
  },
  {
    evtId: 403,
    evtDate: "2024-02-05",
    evtHPos: 3,
    evtDuration: 1,
    classDesc: "3A",
    authorName: "Prof. Rossi",
    subjectId: 3,
    subjectCode: "STO",
    subjectDesc: "Storia",
    lessonType: "Lezione",
    lessonArg: "La Prima Guerra Mondiale: cause e conseguenze",
  },
]

export const mockNotices: Notice[] = [
  {
    pubId: 501,
    pubDT: "2024-02-01T09:00:00",
    readStatus: false,
    evtCode: "GEN",
    cntValidFrom: "2024-02-01T00:00:00",
    cntValidTo: "2024-02-15T23:59:59",
    cntValidInRange: true,
    cntStatus: "attivo",
    cntTitle: "Riunione genitori-insegnanti",
    cntCategory: "generale",
    cntHasChanged: false,
    cntHasAttach: false,
    needJoin: false,
    needReply: false,
    needFile: false,
    evento_id: 501,
  },
  {
    pubId: 502,
    pubDT: "2024-01-28T14:30:00",
    readStatus: true,
    evtCode: "DID",
    cntValidFrom: "2024-01-28T00:00:00",
    cntValidTo: "2024-02-28T23:59:59",
    cntValidInRange: true,
    cntStatus: "attivo",
    cntTitle: "Nuovi orari biblioteca",
    cntCategory: "didattica",
    cntHasChanged: false,
    cntHasAttach: true,
    needJoin: false,
    needReply: false,
    needFile: false,
    evento_id: 502,
  },
]

export const mockSubjects: Subject[] = [
  {
    id: 1,
    description: "Matematica",
    order: 1,
    teachers: [
      {
        teacherId: 101,
        teacherName: "Prof. Bianchi",
        teacherFirstName: "Marco",
        teacherLastName: "Bianchi",
      },
    ],
  },
  {
    id: 2,
    description: "Italiano",
    order: 2,
    teachers: [
      {
        teacherId: 102,
        teacherName: "Prof. Verdi",
        teacherFirstName: "Anna",
        teacherLastName: "Verdi",
      },
    ],
  },
  {
    id: 3,
    description: "Storia",
    order: 3,
    teachers: [
      {
        teacherId: 103,
        teacherName: "Prof. Rossi",
        teacherFirstName: "Giuseppe",
        teacherLastName: "Rossi",
      },
    ],
  },
  {
    id: 4,
    description: "Inglese",
    order: 4,
    teachers: [
      {
        teacherId: 104,
        teacherName: "Prof. Smith",
        teacherFirstName: "John",
        teacherLastName: "Smith",
      },
    ],
  },
]
